# Generated by Django 5.2.7 on 2025-10-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loanapplication_outstanding_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_usage_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly mobile usage (MWK)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proof_documents',
            field=models.FileField(blank=True, help_text='Upload proof (e.g., bank statement, utility bill)', null=True, upload_to='user_proofs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='utility_bills_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly utility bills (MWK)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Mobile Top-up', 'Mobile Top-up'), ('Utility Payment', 'Utility Payment')], max_length=20),
        ),
    ]
