# Generated by Django 5.2.7 on 2025-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_mobile_usage_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Unique transaction reference number (e.g., from bank)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, help_text='Source of transaction (e.g., Airtel, TNM, Bank)', max_length=100, null=True),
        ),
    ]
